# used a dictionary to represent an intents JSON file
data = {"intents": [
{"tag": "greeting",
 "responses": ["Hello", "How are you doing?",   "Greetings!", "How do you do?", "i'm Here to assist You"]},
{"tag": "age",
 "responses": ["I am 25 years old", "I was born in 1998", "My birthday is July 3rd and I was born in 1998", "03/07/1998"]},
{"tag": "date",
 "responses": ["I am available all week", "I don't have any plans",  "I am not busy"]},
{"tag": "name",
 "responses": ["My name Testbot", "I'm Testbot", "Youcan call me Testbot"]},
{"tag": "goodbye",
 "responses": ["It was nice speaking to you", "See you later", "Speak soon!"]},
{"tag": "appointment_booking",
 "responses": ["Sure, let's schedule that for you.", "I can help you with appointment booking.", "Absolutely, I'll assist you with scheduling.", "Let's find a suitable time for your appointment.", "Booking an appointment is no problem.", "Certainly, we can set up an appointment.", "I'm here to help you book your appointment.", "Booking a consultation is easy with me.", "I'll guide you through the appointment booking process.", "Feel free to let me know your preferred time for the appointment."]},
{"tag": "medical_inquiry",
 "responses": ["I'm not a doctor, but I'll do my best to help.", "It's essential to consult a healthcare professional for accurate advice.", "Consider reaching out to a medical professional for personalized guidance.", "I recommend discussing this with your doctor for precise information.", "While I can provide general information, consulting a healthcare professional is crucial.", "It's important to seek advice from a qualified medical professional regarding your health concerns.", "I'm here to offer support, but please consult with a medical professional for specific health queries.", "For accurate information, it's best to consult with a healthcare professional.", "I'm not a substitute for professional medical advice; consider consulting a doctor for personalized guidance.", "Your health is important. It's advisable to consult with a healthcare professional for personalized assistance."]},
{"tag": "test_results_inquiry",
 "responses": ["I'll check on your test results for you.", "Allow me a moment to retrieve your test results.", "I'll get the information on your test results.", "Let me find your test results for you.", "I'm here to assist with your test results.", "I'll look into your test results shortly.", "I'll provide the details about your test results.", "Just a moment, I'll fetch your test results.", "I'm checking your test results now.", "I'll get back to you with your test results."]},
{"tag": "hospital_facilities",
 "responses": ["Our hospital provides a range of facilities to meet your needs.", "Feel free to explore our various hospital amenities.", "We have state-of-the-art facilities to ensure your comfort.", "Discover the comprehensive facilities we offer at our hospital.", "From modern equipment to dedicated staff, our facilities are designed to serve you.", "Explore the diverse facilities available in our hospital.", "We aim to provide top-notch facilities for your healthcare journey.", "Our hospital is equipped with a variety of amenities for your convenience.", "Discover the range of services and facilities available at our hospital.", "We strive to make your experience comfortable with our excellent facilities."]},
{"tag": "health_advice",
 "responses": ["Maintaining a balanced diet is crucial for good health.", "Regular exercise is essential for a healthy lifestyle.", "Adequate sleep is important for overall well-being.", "Stay hydrated throughout the day for optimal health.", "Consult with a healthcare professional for personalized health advice.", "Managing stress is key to maintaining good health.", "Preventive care plays a significant role in long-term well-being.", "Incorporate fruits and vegetables into your daily diet.", "Physical activity is essential for cardiovascular health.", "Listen to your body and seek medical advice if needed."]},
{"tag": "billing_and_payments",
 "responses": ["For billing inquiries, please contact our billing department.", "You can find information about payments on our website.", "Feel free to inquire about your medical bills at our billing desk.", "We're here to help with any questions regarding payments.", "For billing assistance, visit our customer service center.", "Information about payments can be found on our official website.", "Feel free to ask about billing-related concerns at the front desk.", "We're available to assist you with any billing or payment inquiries.", "You can get details about payments by calling our customer support.", "Feel free to inquire about payment options and billing details."]},
{"tag": "hospital_location",
 "responses": ["The hospital is located at [Address].", "You can find us at [Address].", "Our hospital is situated at [Address].", "The address of the hospital is [Address].", "You'll find our hospital at [Address].", "Our location is [Address].", "We are located at [Address].", "You can visit us at [Address].", "The hospital's address is [Address].", "Our location can be found at [Address]."]},
{"tag": "other",
 "responses": ["I'll do my best to help you.", "Feel free to ask anything.", "I'm here to assist you.", "Let me know if you have more questions.", "Ask away!", "I'm here for any inquiries.", "Feel free to inquire about anything.", "I'm at your service.", "Ask me anything!", "I'm here to provide information."]},
]}